-- MySQL Script generated by MySQL Workbench
-- 09/17/15 21:26:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user` (
  `int_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `vchr_username` VARCHAR(50) NULL COMMENT '',
  `vchr_password` VARCHAR(255) NULL COMMENT '',
  `vchr_email` VARCHAR(45) NULL COMMENT '',
  `vchr_name` VARCHAR(250) NULL COMMENT '',
  `vchr_lastname` VARCHAR(250) NULL COMMENT '',
  `vchr_city` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`int_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_group` (
  `int_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `vchr_name` VARCHAR(90) NULL COMMENT '',
  PRIMARY KEY (`int_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user_group` (
  `int_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `int_id_usuario` INT NOT NULL COMMENT '',
  `int_id_grupo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`int_id`)  COMMENT '',
  INDEX `fk_tb_user_group_tb_group1_idx` (`int_id_grupo` ASC)  COMMENT '',
  INDEX `fk_tb_user_group_tb_user1_idx` (`int_id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_user_group_tb_group1`
    FOREIGN KEY (`int_id_grupo`)
    REFERENCES `mydb`.`tb_group` (`int_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_group_tb_user1`
    FOREIGN KEY (`int_id_usuario`)
    REFERENCES `mydb`.`tb_user` (`int_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_user_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user_position` (
  `int_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `int_id_user` INT NOT NULL COMMENT '',
  `vchr_position` VARCHAR(5900) NULL COMMENT '',
  PRIMARY KEY (`int_id`)  COMMENT '',
  INDEX `fk_tb_user_position_tb_user_idx` (`int_id_user` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_user_position_tb_user`
    FOREIGN KEY (`int_id_user`)
    REFERENCES `mydb`.`tb_user` (`int_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
